constants:
  sample_interval: 1/24
  name: "MIXSED2"
  ind: [30,38] #expect name_000.hex
  convert: 'yes'
  time_ref: 'System UTC'
  data_dir: "/Volumes/T9ifmeo/odb2026/CTD/raw"
  output_dir: "/Volumes/T9ifmeo/odb2026/CTD/ctdproc_nc"

features:
#  - name: "align"
#    variables: ["conductivity","conductivity2"]
#    offset: [0.073,0.073]  # 
#  - name: "wild_edit"
#    variables: ["temperature","temperature2","conductivity","conductivity2","pressure"]
#    std_pass_1: [2.0,2.0,2.0,2.0,2.0]
#    std_pass_2: [5.0,5.0,5.0,5.0,5.0]
#    scans_per_block: [100,100,100,100,100]
#    distance_to_mean: [0.0,0.0,0.0,0.0,0.0]
#  - name: "low_filter"
#    variables:  ["pressure","temperature","conductivity"]
#    time_constant: [0.03,0.03,0.03]
#  - name: "celltm"
#    variables: ["conductivity","conductivity2"]
#    amplitude: [0.03,0.03]
#    time_constant: [7.0,7.0]
#  - name: "loop_edit"
#    min_velocity: [0.25]
#    window_size: [3]
#    mean_speed_percent: [20]
#    remove_surface_soak: [True]
#    min_soak_depth: [5]
#    max_soak_depth: [20]
#    use_deck_pressure_offset: [False]
#  - name: "bin"
#    bin_type: ["scans","pressure"]
#    bin_size: [24.0,1.0]
#    type_profile: ["BOTH",'DOWN']
